
require 'pathname'

project_dir = Pathname.new "."
json_file = project_dir.join('image_set.json')

photoscan="/opt/photoscan-pro/photoscan.sh"
photoscan_py = "../../photoscan_scripts/photoscan.py"

task :extract do

  sh "#{ENV['GOPATH']}/bin/extract_set",
      '-delete',
      json_file.to_s

end

task :photoscan do

  sh photoscan, '-r', photoscan_py,
      '--align',
      json_file.to_s
end
